//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUAsistencia
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.Informe = new HashSet<Informe>();
        }
    
        public int id_emp { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los nombres son requeridos"), MaxLength(100)]
        [Display(Name = "Nombres")]
        public string nombre_completo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El telefono es requerido"), MaxLength(15)]
        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El email es requerido"), MaxLength(25)]
        [Display(Name = "Email")]
        public string correo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La cedula es requerida"), MaxLength(13)]
        [Display(Name = "Cédula")]
        public string cedula { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El lugar de nacimiento es requerido"), MaxLength(55)]
        [Display(Name = "Lugar de Nacimiento")]
        public string lugar_nacimiento { get; set; }
        [Display(Name ="Sexo")]
        public string sexo { get; set; }
        [Display(Name ="Estado Civil")]
        public string estado_civil { get; set; }
        [Display(Name ="Area de Trabajo")]
        public string area_trabajo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe> Informe { get; set; }
    }
}
