//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUAsistencia
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Informe
    {
        public int id { get; set; }
        [Display(Name ="Pago Empleado")]
        public Nullable<double> pago_empleado { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<int> id_asis { get; set; }
        [Display(Name ="Empleado")]
        public Nullable<int> id_emp { get; set; }
        [Display(Name ="Dias Trabajados")]
        public Nullable<double> dias_trabajo { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
